"""Post-process saved task-level trajectories by inserting canonical get_image steps."""

from __future__ import annotations

import json
from dataclasses import dataclass
import shutil
from pathlib import Path
from typing import Any

from data_generation.task_level.generation.raw.progress import (
    _close_progress_handles,
    _create_progress_handles,
)
from data_generation.utils import stable_json_sha256, write_json_output

GET_IMAGE_TOOL_NAME = "get_image"
COMMUNICATE_TOOL_NAME = "communicate"
BASE_CAMERA_VIEW = "base_camera"
TOP_VIEW_CAMERA = "top_view"
POST_PROCESS_ERROR_EXIT_CODE = 1
INITIAL_GET_IMAGE_REASONING_BY_CAMERA = {
    TOP_VIEW_CAMERA: "I need an initial top-view image before the task begins.",
}
BASE_CAMERA_REASONING_TEMPLATES = {
    "before": (
        "I need a base-camera image to observe the current scene before I execute "
        "{tool}."
    ),
    "after": (
        "I need a base-camera image to observe the current scene after I executed "
        "{tool}."
    ),
}
POST_PROCESS_VALIDATION_ERROR_TYPE = "PostProcessingValidationRequired"
POST_PROCESS_VALIDATION_ERROR = (
    "Trajectory was post-processed after validation and must be revalidated."
)


@dataclass(frozen=True)
class PostProcessRuntimeConfig:
    """Stores the minimal progress configuration needed by the shared UI helpers."""

    num_trajectories: int
    max_retries: int = 1


def build_step_image_path(
    trajectory_id: str,
    step_index: int,
    agent_id: str,
    camera_view: str,
) -> str:
    """Builds the deterministic relative image path for one inserted get_image step."""

    filename = f"{step_index}_{camera_view}_{agent_id}.png"
    return (Path("images") / trajectory_id / filename).as_posix()


def _copy_step_without_generated_fields(step: dict[str, Any]) -> dict[str, Any]:
    """Copies a persisted step while dropping fields regenerated by post-processing."""

    copied_step = dict(step)
    copied_step.pop("image_path", None)
    return copied_step


def _build_base_camera_reasoning(tool_name: str, *, timing: str) -> str:
    """Builds direction-aware reasoning for base-camera snapshots around actions."""

    template = BASE_CAMERA_REASONING_TEMPLATES.get(timing)
    if template is None:
        raise ValueError(f"Unsupported base-camera timing: {timing}")
    return template.format(tool=tool_name)


def _build_get_image_step(
    agent_id: str,
    *,
    camera_view: str,
    wrapped_tool_name: str | None = None,
    timing: str | None = None,
) -> dict[str, Any]:
    """Builds one synthetic get_image step inserted around action tool calls."""

    if camera_view == BASE_CAMERA_VIEW:
        if not wrapped_tool_name:
            raise ValueError("Base-camera get_image steps require a wrapped tool.")
        if timing is None:
            raise ValueError("Base-camera get_image steps require a timing value.")
        reasoning = _build_base_camera_reasoning(wrapped_tool_name, timing=timing)
    else:
        reasoning = INITIAL_GET_IMAGE_REASONING_BY_CAMERA[camera_view]

    return {
        "step": -1,
        "agent": agent_id,
        "tool": GET_IMAGE_TOOL_NAME,
        "args": {"camera_view": camera_view},
        "reasoning": reasoning,
    }


def rebuild_steps_with_get_image(
    steps: list[dict[str, Any]],
    *,
    initial_image_agent_id: str,
    trajectory_id: str,
) -> list[dict[str, Any]]:
    """Rebuilds one step list so every non-communicate action is bracketed by get_image."""

    # Seed each rewritten trajectory with one shared scene snapshot before any
    # agent starts acting.
    rebuilt_steps: list[dict[str, Any]] = [
        _build_get_image_step(
            initial_image_agent_id,
            camera_view=TOP_VIEW_CAMERA,
        )
    ]
    for step in steps:
        tool_name = step.get("tool")
        if tool_name == GET_IMAGE_TOOL_NAME:
            # Drop existing get_image steps so reruns stay idempotent.
            continue

        copied_step = _copy_step_without_generated_fields(step)
        if tool_name == COMMUNICATE_TOOL_NAME:
            rebuilt_steps.append(copied_step)
            continue

        agent_id = copied_step.get("agent")
        if not isinstance(agent_id, str) or not agent_id:
            raise ValueError(
                "Every non-communicate step must contain a non-empty agent."
            )

        rebuilt_steps.append(
            _build_get_image_step(
                agent_id,
                camera_view=BASE_CAMERA_VIEW,
                wrapped_tool_name=tool_name,
                timing="before",
            )
        )
        rebuilt_steps.append(copied_step)
        rebuilt_steps.append(
            _build_get_image_step(
                agent_id,
                camera_view=BASE_CAMERA_VIEW,
                wrapped_tool_name=tool_name,
                timing="after",
            )
        )

    # Renumber after insertion so saved step indices and image filenames stay
    # deterministic regardless of the input shape.
    for step_index, step in enumerate(rebuilt_steps):
        step["step"] = step_index
        if step["tool"] == GET_IMAGE_TOOL_NAME:
            step["image_path"] = build_step_image_path(
                trajectory_id,
                step["step"],
                step["agent"],
                step["args"]["camera_view"],
            )
        else:
            step.pop("image_path", None)
    return rebuilt_steps


def _resolve_initial_image_agent_id(trajectory: dict[str, Any]) -> str:
    """Chooses which agent owns the prepended top_view snapshot."""

    for step in trajectory.get("steps", ()):
        tool_name = step.get("tool")
        agent_id = step.get("agent")
        if tool_name == GET_IMAGE_TOOL_NAME:
            continue
        if isinstance(agent_id, str) and agent_id:
            return agent_id

    for agent in trajectory.get("agents", ()):
        agent_id = agent.get("agent")
        if isinstance(agent_id, str) and agent_id:
            return agent_id

    raise ValueError("Trajectory records must contain at least one valid agent.")


def _normalized_signature_payload(trajectory: dict[str, Any]) -> dict[str, Any]:
    """Builds the stable signature payload used by validated saved trajectories."""

    return {
        "agents": sorted(
            trajectory.get("agents", ()),
            key=lambda agent: agent["agent"],
        ),
        "steps": sorted(
            trajectory.get("steps", ()),
            key=lambda step: step["step"],
        ),
    }


def _replace_validation_with_post_process_status(trajectory: dict[str, Any]) -> None:
    """Replaces stale validation metadata after post-processing rewrites the steps."""

    validation = trajectory.get("validation")
    if not isinstance(validation, dict):
        return
    trajectory["validation"] = {
        "is_valid": False,
        "checks": [],
        "final_state": None,
        "error_type": POST_PROCESS_VALIDATION_ERROR_TYPE,
        "error": POST_PROCESS_VALIDATION_ERROR,
        "step": None,
        "signature": stable_json_sha256(_normalized_signature_payload(trajectory)),
    }


def post_process_trajectory(trajectory: dict[str, Any]) -> dict[str, Any]:
    """Returns one rewritten trajectory record with inserted get_image steps."""

    if not isinstance(trajectory.get("steps"), list):
        raise ValueError("Trajectory records must contain a steps list.")
    trajectory_id = trajectory.get("trajectory_id")
    if not isinstance(trajectory_id, str) or not trajectory_id:
        raise ValueError("Trajectory records must contain a non-empty trajectory_id.")

    updated_trajectory = dict(trajectory)
    updated_trajectory["steps"] = rebuild_steps_with_get_image(
        updated_trajectory["steps"],
        initial_image_agent_id=_resolve_initial_image_agent_id(updated_trajectory),
        trajectory_id=trajectory_id,
    )
    _replace_validation_with_post_process_status(updated_trajectory)
    return updated_trajectory


def _load_json_file(path: Path) -> dict[str, Any]:
    """Loads one JSON file and validates that the top-level payload is an object."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a top-level JSON object.")
    return payload


def resolve_output_dataset_path(dataset_path: Path) -> Path:
    """Maps one source dataset path to the default copied w_images destination."""

    resolved_path = dataset_path.resolve()
    parts = list(resolved_path.parts)
    try:
        data_index = parts.index("data")
    except ValueError:
        return dataset_path.parent / "w_images" / dataset_path.name

    relative_parts = parts[data_index + 1 :]
    if relative_parts and relative_parts[0] in {"raw", "w_images"}:
        relative_parts = relative_parts[1:]
    return Path(*parts[: data_index + 1]) / "w_images" / Path(*relative_parts)


def _resolve_output_image_dir(output_dataset_path: Path) -> Path:
    """Resolves the sibling image directory referenced by inserted get_image steps."""

    return output_dataset_path.parent / "images"


def _resolve_summary_trajectory_paths(
    dataset_path: Path, payload: dict[str, Any]
) -> list[Path]:
    """Resolves trajectory file paths referenced by a summary dataset JSON."""

    trajectory_files = payload.get("trajectory_files")
    if not isinstance(trajectory_files, list):
        raise ValueError(
            "Summary datasets must contain a trajectory_files list of relative JSON paths."
        )

    resolved_paths: list[Path] = []
    for entry in trajectory_files:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            raise ValueError("Each trajectory_files entry must contain a string path.")
        resolved_paths.append((dataset_path.parent / entry["path"]).resolve())
    return resolved_paths


def _post_process_summary_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
) -> int:
    """Writes a copied summary dataset tree and post-processes its trajectories."""

    if output_dataset_path.resolve() != dataset_path.resolve():
        # Copy the whole dataset tree first so relative artifact paths remain
        # valid after trajectory files are rewritten in place.
        shutil.copytree(
            dataset_path.parent,
            output_dataset_path.parent,
            dirs_exist_ok=True,
        )
        payload = _load_json_file(output_dataset_path)

    # Post-processing only inserts deterministic image references, but later
    # rendering stages expect the sibling image root to exist up front.
    _resolve_output_image_dir(output_dataset_path).mkdir(parents=True, exist_ok=True)
    trajectory_paths = _resolve_summary_trajectory_paths(output_dataset_path, payload)
    progress_handles = _create_progress_handles(
        PostProcessRuntimeConfig(num_trajectories=len(trajectory_paths)),
        disable_progress=disable_progress,
    )
    try:
        for index, trajectory_path in enumerate(trajectory_paths):
            trajectory_progress = progress_handles.trajectory_progress_bars[index]
            trajectory_progress.set_postfix_str("processing")
            trajectory = _load_json_file(trajectory_path)
            updated_trajectory = post_process_trajectory(trajectory)
            write_json_output(updated_trajectory, trajectory_path)
            trajectory_progress.update(1)
            trajectory_progress.set_postfix_str(
                f"done calls={len(updated_trajectory['steps'])}"
            )
            progress_handles.overall_progress.update(1)
        write_json_output(payload, output_dataset_path)
    finally:
        _close_progress_handles(progress_handles)
    return len(trajectory_paths)


def _post_process_payload_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
) -> int:
    """Writes a copied inline dataset payload with post-processed trajectories."""

    trajectories = payload.get("trajectories")
    if not isinstance(trajectories, list):
        raise ValueError(
            "Inline datasets must contain a trajectories list or trajectory_files list."
        )

    progress_handles = _create_progress_handles(
        PostProcessRuntimeConfig(num_trajectories=len(trajectories)),
        disable_progress=disable_progress,
    )
    try:
        # Keep inline-dataset outputs aligned with the summary-dataset layout so
        # downstream image rendering can use the same sibling image directory.
        _resolve_output_image_dir(output_dataset_path).mkdir(parents=True, exist_ok=True)
        updated_trajectories: list[dict[str, Any]] = []
        for index, trajectory in enumerate(trajectories):
            trajectory_progress = progress_handles.trajectory_progress_bars[index]
            trajectory_progress.set_postfix_str("processing")
            updated_trajectory = post_process_trajectory(trajectory)
            updated_trajectories.append(updated_trajectory)
            trajectory_progress.update(1)
            trajectory_progress.set_postfix_str(
                f"done calls={len(updated_trajectory['steps'])}"
            )
            progress_handles.overall_progress.update(1)
        payload["trajectories"] = updated_trajectories
        write_json_output(payload, output_dataset_path)
    finally:
        _close_progress_handles(progress_handles)
    return len(trajectories)


def post_process_dataset(
    dataset_path: Path,
    *,
    output_dataset_path: Path | None = None,
    disable_progress: bool = False,
) -> int:
    """Post-processes one dataset into a copied output JSON and returns the count."""

    output_dataset_path = output_dataset_path or resolve_output_dataset_path(
        dataset_path
    )
    payload = _load_json_file(dataset_path)
    if "trajectory_files" in payload:
        return _post_process_summary_dataset(
            dataset_path,
            payload,
            output_dataset_path=output_dataset_path,
            disable_progress=disable_progress,
        )
    return _post_process_payload_dataset(
        dataset_path,
        payload,
        output_dataset_path=output_dataset_path,
        disable_progress=disable_progress,
    )
