"""Post-process saved task-level trajectories by inserting observation steps."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
import shutil
from typing import Any, Sequence

from data_generation.task_level.generation.raw.progress import (
    _close_progress_handles,
    _create_progress_handles,
)
from data_generation.task_level.tasks.shared.constants import NAVIGATION_TOOL_NAMES
from data_generation.utils import stable_json_sha256, write_json_output

GET_IMAGE_TOOL_NAME = "get_image"
LEGACY_ENV_IMAGE_TOOL_NAME = "get_env_image"
LEGACY_AGENT_IMAGE_TOOL_NAME = "get_agent_image"
COMMUNICATE_TOOL_NAME = "communicate"
TOP_VIEW_CAMERA = "top_view"
ROOM_VIEW_CAMERA = "room_view"
MAP_VIEW = "map"
WRIST_CAMERA = "wrist"
AGENT_VIEW_CENTER_CAMERA = "agentview_center"
AGENT_VIEW_LEFT_CAMERA = "agentview_left"
AGENT_VIEW_RIGHT_CAMERA = "agentview_right"
INITIAL_OBSERVATION_VIEWS = (
    TOP_VIEW_CAMERA,
    ROOM_VIEW_CAMERA,
    MAP_VIEW,
)
NAVIGATION_OBSERVATION_VIEWS = (
    AGENT_VIEW_CENTER_CAMERA,
    AGENT_VIEW_LEFT_CAMERA,
    AGENT_VIEW_RIGHT_CAMERA,
)
ACTION_OBSERVATION_VIEWS = (
    WRIST_CAMERA,
    AGENT_VIEW_CENTER_CAMERA,
)
LEGACY_INSERTED_OBSERVATION_TOOL_NAMES = frozenset(
    {
        GET_IMAGE_TOOL_NAME,
        LEGACY_ENV_IMAGE_TOOL_NAME,
        LEGACY_AGENT_IMAGE_TOOL_NAME,
    }
)
VIEW_REASONING_LABELS = {
    TOP_VIEW_CAMERA: "top-view",
    ROOM_VIEW_CAMERA: "room-view",
    MAP_VIEW: "map",
    WRIST_CAMERA: "wrist",
    AGENT_VIEW_CENTER_CAMERA: "center agent-view",
    AGENT_VIEW_LEFT_CAMERA: "left agent-view",
    AGENT_VIEW_RIGHT_CAMERA: "right agent-view",
}
ACTION_IMAGE_REASONING_TEMPLATES = {
    "before": (
        "I need {view_labels} images to observe the current scene before I "
        "execute {tool}."
    ),
    "after": (
        "I need {view_labels} images to observe the current scene after I "
        "executed {tool}."
    ),
}
POST_PROCESS_ERROR_EXIT_CODE = 1
POST_PROCESS_VALIDATION_ERROR_TYPE = "PostProcessingValidationRequired"
POST_PROCESS_VALIDATION_ERROR = (
    "Trajectory was post-processed after validation and must be revalidated."
)
RAW_DATASET_DIRECTORY_NAME = "raw"
IMAGE_DATASET_DIRECTORY_NAME = "image"
LEGACY_IMAGE_OUTPUT_DIRECTORY_NAME = "w_images"


@dataclass(frozen=True)
class PostProcessRuntimeConfig:
    """Stores the minimal progress configuration needed by the shared UI helpers."""

    num_trajectories: int
    num_runs: int | None = None
    max_retries: int = 1
    run_indices: tuple[int, ...] = ()
    sampling: str = "base"
    batch_processing: bool = False

    def __post_init__(self) -> None:
        """Keeps the lightweight progress config aligned with raw runtime helpers."""

        if self.num_runs is None:
            object.__setattr__(self, "num_runs", self.num_trajectories)


def build_step_image_path(
    trajectory_id: str,
    step_index: int,
    agent_id: str,
    view_name: str,
    *,
    tool_name: str = GET_IMAGE_TOOL_NAME,
) -> str:
    """Builds the deterministic relative image path for one inserted view."""

    # Keep the helper signature stable even though post-processing now emits
    # only the unified get_image layout.
    _ = tool_name
    filename = f"{step_index}_{view_name}_{agent_id}.png"
    return (Path("images") / trajectory_id / filename).as_posix()


def _build_step_image_paths(
    trajectory_id: str,
    step_index: int,
    agent_id: str,
    view_names: Sequence[str],
) -> list[str]:
    """Builds the ordered image paths for one multi-view get_image step."""

    return [
        build_step_image_path(
            trajectory_id,
            step_index,
            agent_id,
            view_name,
        )
        for view_name in view_names
    ]


def _copy_step_without_generated_fields(step: dict[str, Any]) -> dict[str, Any]:
    """Copies a persisted step while dropping fields regenerated by post-processing."""

    copied_step = dict(step)
    copied_step.pop("image_path", None)
    copied_step.pop("image_paths", None)
    return copied_step


def _format_view_labels(view_names: Sequence[str]) -> str:
    """Formats a stable human-readable label for one or more requested views."""

    formatted_labels: list[str] = []
    for view_name in view_names:
        view_label = VIEW_REASONING_LABELS.get(view_name)
        if view_label is None:
            raise ValueError(f"Unsupported get_image view: {view_name}")
        formatted_labels.append(view_label)

    if len(formatted_labels) == 1:
        return formatted_labels[0]
    if len(formatted_labels) == 2:
        return f"{formatted_labels[0]} and {formatted_labels[1]}"
    return ", ".join(formatted_labels[:-1]) + f", and {formatted_labels[-1]}"


def _build_action_get_image_reasoning(
    tool_name: str,
    *,
    timing: str,
    view_names: Sequence[str],
) -> str:
    """Builds direction-aware reasoning for one aggregated get_image step."""

    template = ACTION_IMAGE_REASONING_TEMPLATES.get(timing)
    if template is None:
        raise ValueError(f"Unsupported get_image timing: {timing}")
    return template.format(
        tool=tool_name,
        view_labels=_format_view_labels(view_names),
    )


def _build_get_image_step(
    agent_id: str,
    *,
    view_names: Sequence[str],
    reasoning: str,
) -> dict[str, Any]:
    """Builds one synthetic get_image step with a normalized views list."""

    return {
        "step": -1,
        "agent": agent_id,
        "tool": GET_IMAGE_TOOL_NAME,
        "args": {"views": list(view_names)},
        "reasoning": reasoning,
    }


def _build_initial_observation_step(agent_id: str) -> dict[str, Any]:
    """Builds the shared initial scene-inspection observation step."""

    return _build_get_image_step(
        agent_id,
        view_names=INITIAL_OBSERVATION_VIEWS,
        reasoning=(
            "I need top-view, room-view, and map images before the task begins."
        ),
    )


def _resolve_initial_observation_insert_index(
    steps: Sequence[dict[str, Any]],
) -> int:
    """Finds where the shared opening observations should be inserted."""

    insert_index = 0
    for step in steps:
        if step.get("tool") != COMMUNICATE_TOOL_NAME:
            break
        insert_index += 1
    return insert_index


def _resolve_action_view_names(tool_name: str) -> tuple[str, ...]:
    """Chooses the inserted observation views for one wrapped action tool."""

    if tool_name in NAVIGATION_TOOL_NAMES:
        return NAVIGATION_OBSERVATION_VIEWS
    return ACTION_OBSERVATION_VIEWS


def _build_action_observation_step(
    agent_id: str,
    *,
    tool_name: str,
    timing: str,
) -> dict[str, Any]:
    """Builds one aggregated observation step around an action tool call."""

    view_names = _resolve_action_view_names(tool_name)
    return _build_get_image_step(
        agent_id,
        view_names=view_names,
        reasoning=_build_action_get_image_reasoning(
            tool_name,
            timing=timing,
            view_names=view_names,
        ),
    )


def _resolve_observation_step_view_names(step: dict[str, Any]) -> tuple[str, ...]:
    """Extracts the normalized ordered view names for one inserted get_image step."""

    args = step.get("args")
    if not isinstance(args, dict):
        raise ValueError("Inserted get_image steps must contain an args object.")

    view_names = args.get("views")
    if not isinstance(view_names, list) or not all(
        isinstance(view_name, str) for view_name in view_names
    ):
        raise ValueError(
            "Inserted get_image steps must contain args.views as a string list."
        )
    return tuple(view_names)


def rebuild_steps_with_image_observations(
    steps: list[dict[str, Any]],
    *,
    initial_image_agent_ids: Sequence[str],
    trajectory_id: str,
) -> list[dict[str, Any]]:
    """Rebuilds one step list with deterministic inserted observation steps."""

    cleaned_steps: list[dict[str, Any]] = []
    for step in steps:
        tool_name = step.get("tool")
        if tool_name in LEGACY_INSERTED_OBSERVATION_TOOL_NAMES:
            # Drop existing synthetic observation steps so reruns stay idempotent
            # and old split-tool outputs can be upgraded in one pass.
            continue

        cleaned_steps.append(_copy_step_without_generated_fields(step))

    initial_observation_insert_index = _resolve_initial_observation_insert_index(
        cleaned_steps
    )
    rebuilt_steps = cleaned_steps[:initial_observation_insert_index]
    # Keep the opening observations together after the initial coordination
    # block so every agent captures the shared scene before the first task action.
    rebuilt_steps.extend(
        _build_initial_observation_step(agent_id)
        for agent_id in initial_image_agent_ids
    )
    for copied_step in cleaned_steps[initial_observation_insert_index:]:
        tool_name = copied_step.get("tool")
        if tool_name == COMMUNICATE_TOOL_NAME:
            rebuilt_steps.append(copied_step)
            continue

        agent_id = copied_step.get("agent")
        if not isinstance(agent_id, str) or not agent_id:
            raise ValueError(
                "Every non-communicate step must contain a non-empty agent."
            )

        rebuilt_steps.append(
            _build_action_observation_step(
                agent_id,
                tool_name=tool_name,
                timing="before",
            )
        )
        rebuilt_steps.append(copied_step)
        rebuilt_steps.append(
            _build_action_observation_step(
                agent_id,
                tool_name=tool_name,
                timing="after",
            )
        )

    # Renumber after insertion so saved step indices and image filenames stay
    # deterministic regardless of the input shape.
    for step_index, step in enumerate(rebuilt_steps):
        step["step"] = step_index
        if step["tool"] == GET_IMAGE_TOOL_NAME:
            view_names = _resolve_observation_step_view_names(step)
            step["image_paths"] = _build_step_image_paths(
                trajectory_id,
                step["step"],
                step["agent"],
                view_names,
            )
            step.pop("image_path", None)
            continue
        step.pop("image_path", None)
        step.pop("image_paths", None)
    return rebuilt_steps


def _append_unique_agent_id(
    agent_ids: list[str],
    seen_agent_ids: set[str],
    agent_id: Any,
) -> None:
    """Appends a non-empty agent ID once while preserving its discovery order."""

    if not isinstance(agent_id, str) or not agent_id or agent_id in seen_agent_ids:
        return
    seen_agent_ids.add(agent_id)
    agent_ids.append(agent_id)


def _resolve_initial_image_agent_ids(trajectory: dict[str, Any]) -> tuple[str, ...]:
    """Chooses which agents receive the opening shared-scene observations."""

    resolved_agent_ids: list[str] = []
    seen_agent_ids: set[str] = set()
    for agent in trajectory.get("agents", ()):
        _append_unique_agent_id(
            resolved_agent_ids,
            seen_agent_ids,
            agent.get("agent"),
        )

    for step in trajectory.get("steps", ()):
        if step.get("tool") in LEGACY_INSERTED_OBSERVATION_TOOL_NAMES:
            continue
        _append_unique_agent_id(
            resolved_agent_ids,
            seen_agent_ids,
            step.get("agent"),
        )

    if resolved_agent_ids:
        return tuple(resolved_agent_ids)

    raise ValueError("Trajectory records must contain at least one valid agent.")


def _normalized_signature_payload(trajectory: dict[str, Any]) -> dict[str, Any]:
    """Builds the stable signature payload used by validated saved trajectories."""

    return {
        "agents": sorted(
            trajectory.get("agents", ()),
            key=lambda agent: agent["agent"],
        ),
        "steps": sorted(
            trajectory.get("steps", ()),
            key=lambda step: step["step"],
        ),
    }


def _replace_validation_with_post_process_status(trajectory: dict[str, Any]) -> None:
    """Replaces stale validation metadata after post-processing rewrites the steps."""

    validation = trajectory.get("validation")
    if not isinstance(validation, dict):
        return
    trajectory["validation"] = {
        "is_valid": False,
        "checks": [],
        "final_state": None,
        "error_type": POST_PROCESS_VALIDATION_ERROR_TYPE,
        "error": POST_PROCESS_VALIDATION_ERROR,
        "step": None,
        "signature": stable_json_sha256(_normalized_signature_payload(trajectory)),
    }


def post_process_trajectory(
    trajectory: dict[str, Any],
) -> dict[str, Any]:
    """Returns one rewritten trajectory record with inserted observation steps."""

    if not isinstance(trajectory.get("steps"), list):
        raise ValueError("Trajectory records must contain a steps list.")
    trajectory_id = trajectory.get("trajectory_id")
    if not isinstance(trajectory_id, str) or not trajectory_id:
        raise ValueError("Trajectory records must contain a non-empty trajectory_id.")

    updated_trajectory = dict(trajectory)
    updated_trajectory["steps"] = rebuild_steps_with_image_observations(
        updated_trajectory["steps"],
        initial_image_agent_ids=_resolve_initial_image_agent_ids(updated_trajectory),
        trajectory_id=trajectory_id,
    )
    _replace_validation_with_post_process_status(updated_trajectory)
    return updated_trajectory


def _load_json_file(path: Path) -> dict[str, Any]:
    """Loads one JSON file and validates that the top-level payload is an object."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a top-level JSON object.")
    return payload


def resolve_output_dataset_path(dataset_path: Path) -> Path:
    """Maps one source dataset path to the default copied image destination."""

    resolved_path = dataset_path.resolve()
    parts = list(resolved_path.parts)
    try:
        data_index = parts.index("data")
    except ValueError:
        return dataset_path.parent / IMAGE_DATASET_DIRECTORY_NAME / dataset_path.name

    relative_parts = parts[data_index + 1 :]
    if not relative_parts:
        return dataset_path.parent / IMAGE_DATASET_DIRECTORY_NAME / dataset_path.name

    if len(relative_parts) >= 2 and relative_parts[0] in {
        RAW_DATASET_DIRECTORY_NAME,
        IMAGE_DATASET_DIRECTORY_NAME,
        LEGACY_IMAGE_OUTPUT_DIRECTORY_NAME,
    }:
        return (
            Path(*parts[: data_index + 1])
            / IMAGE_DATASET_DIRECTORY_NAME
            / relative_parts[1]
            / Path(*relative_parts[2:])
        )
    if len(relative_parts) >= 2 and relative_parts[1] in {
        RAW_DATASET_DIRECTORY_NAME,
        IMAGE_DATASET_DIRECTORY_NAME,
        LEGACY_IMAGE_OUTPUT_DIRECTORY_NAME,
    }:
        return (
            Path(*parts[: data_index + 1])
            / IMAGE_DATASET_DIRECTORY_NAME
            / relative_parts[0]
            / Path(*relative_parts[2:])
        )
    return (
        Path(*parts[: data_index + 1])
        / IMAGE_DATASET_DIRECTORY_NAME
        / Path(*relative_parts)
    )


def _resolve_output_image_dir(output_dataset_path: Path) -> Path:
    """Resolves the sibling image directory referenced by inserted image steps."""

    return output_dataset_path.parent / "images"


def _resolve_summary_trajectory_paths(
    dataset_path: Path, payload: dict[str, Any]
) -> list[Path]:
    """Resolves trajectory file paths referenced by a summary dataset JSON."""

    trajectory_files = payload.get("trajectory_files")
    if not isinstance(trajectory_files, list):
        raise ValueError(
            "Summary datasets must contain a trajectory_files list of relative JSON paths."
        )

    resolved_paths: list[Path] = []
    for entry in trajectory_files:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            raise ValueError("Each trajectory_files entry must contain a string path.")
        resolved_paths.append((dataset_path.parent / entry["path"]).resolve())
    return resolved_paths


def _post_process_summary_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
) -> int:
    """Writes a copied summary dataset tree and post-processes its trajectories."""

    if output_dataset_path.resolve() != dataset_path.resolve():
        # Copy the whole dataset tree first so relative artifact paths remain
        # valid after trajectory files are rewritten in place.
        shutil.copytree(
            dataset_path.parent,
            output_dataset_path.parent,
            dirs_exist_ok=True,
        )
        payload = _load_json_file(output_dataset_path)

    # Post-processing only inserts deterministic image references, but later
    # rendering stages expect the sibling image root to exist up front.
    _resolve_output_image_dir(output_dataset_path).mkdir(parents=True, exist_ok=True)
    trajectory_paths = _resolve_summary_trajectory_paths(output_dataset_path, payload)
    progress_handles = _create_progress_handles(
        PostProcessRuntimeConfig(num_trajectories=len(trajectory_paths)),
        disable_progress=disable_progress,
    )
    try:
        for index, trajectory_path in enumerate(trajectory_paths):
            trajectory_progress = progress_handles.trajectory_progress_bars[index]
            trajectory_progress.set_postfix_str("processing")
            trajectory = _load_json_file(trajectory_path)
            updated_trajectory = post_process_trajectory(trajectory)
            write_json_output(updated_trajectory, trajectory_path)
            trajectory_progress.update(1)
            trajectory_progress.set_postfix_str(
                f"done calls={len(updated_trajectory['steps'])}"
            )
            progress_handles.overall_progress.update(1)
        write_json_output(payload, output_dataset_path)
    finally:
        _close_progress_handles(progress_handles)
    return len(trajectory_paths)


def _post_process_payload_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
) -> int:
    """Writes a copied inline dataset payload with post-processed trajectories."""

    trajectories = payload.get("trajectories")
    if not isinstance(trajectories, list):
        raise ValueError(
            "Inline datasets must contain a trajectories list or trajectory_files list."
        )

    progress_handles = _create_progress_handles(
        PostProcessRuntimeConfig(num_trajectories=len(trajectories)),
        disable_progress=disable_progress,
    )
    try:
        # Keep inline-dataset outputs aligned with the summary-dataset layout so
        # downstream image rendering can use the same sibling image directory.
        _resolve_output_image_dir(output_dataset_path).mkdir(
            parents=True, exist_ok=True
        )
        updated_trajectories: list[dict[str, Any]] = []
        for index, trajectory in enumerate(trajectories):
            trajectory_progress = progress_handles.trajectory_progress_bars[index]
            trajectory_progress.set_postfix_str("processing")
            updated_trajectory = post_process_trajectory(trajectory)
            updated_trajectories.append(updated_trajectory)
            trajectory_progress.update(1)
            trajectory_progress.set_postfix_str(
                f"done calls={len(updated_trajectory['steps'])}"
            )
            progress_handles.overall_progress.update(1)
        payload["trajectories"] = updated_trajectories
        write_json_output(payload, output_dataset_path)
    finally:
        _close_progress_handles(progress_handles)
    return len(trajectories)


def post_process_dataset(
    dataset_path: Path,
    *,
    output_dataset_path: Path | None = None,
    disable_progress: bool = False,
) -> int:
    """Post-processes one dataset into a copied output JSON and returns the count."""

    output_dataset_path = output_dataset_path or resolve_output_dataset_path(
        dataset_path
    )
    payload = _load_json_file(dataset_path)
    if "trajectory_files" in payload:
        return _post_process_summary_dataset(
            dataset_path,
            payload,
            output_dataset_path=output_dataset_path,
            disable_progress=disable_progress,
        )
    return _post_process_payload_dataset(
        dataset_path,
        payload,
        output_dataset_path=output_dataset_path,
        disable_progress=disable_progress,
    )
